# Generated by Django 5.0.1 on 2024-01-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Teacher_id',
            new_name='teacher_id',
        ),
    ]
